name: pytest
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"

      - name: install poetry
        run: |
          python -m pip install poetry
          poetry config virtualenvs.in-project true

      - id: cache-poetry
        uses: actions/cache@v2
        with:
          path: ~/.venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/poetry.lock') }}

      - name: install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          poetry install
      - name: run tests
        run: |
          poetry run pytest src/tests/rl/
